language: java
jdk: oraclejdk8
node_js: lts/*

install: true

script:
- ./gradlew
- ./gradlew dependencyUpdates -Drevision=release

cache:
  directories:
  - web/node_modules/
  - $HOME/.gradle/
  - .gradle/
  - .m2/
